asset_dir = "assets"
write_dir = "src/shared/assets"

[creator]
type = "user"
id = 7473540562

[codegen]
typescript = true
style = "nested"
strip_extensions = true

[inputs.assets]
path = "assets/**/*"
output_path = "src/shared/assets"